Repository Maze7/Tetris, pull requests merged in 2018-09, with the labels that each got.

#1 Added Playfield methods and Tetromino getters
  src/Playfield.cpp
  src/Playfield.h
  src/Tetris.cpp
  src/Tetromino.cpp
  src/Tetromino.h
Labels: enhancement, good first issue

#8 Ft collision preview
  src/GameCollection/Tetris/Game.cpp
  src/GameCollection/Tetris/Game.h
  src/GameCollection/Tetris/Playfield.cpp
  src/GameCollection/Tetris/Playfield.h
  src/GameCollection/Tetris/Tetromino.cpp
  src/GameCollection/Tetris/Tetromino.h
Labels: TetrisModule, enhancement

#10 Score system (based on #9)
  src/GameCollection/Tetris/Game.cpp
  src/GameCollection/Tetris/Game.h
  src/GameCollection/Tetris/Tetromino.h
  src/GameCollection/Tetris/big_noodle_titling.ttf
Labels: TetrisModule, enhancement

#9 Ticks (handleTime) and collision handling
  src/GameCollection/Tetris/Game.cpp
  src/GameCollection/Tetris/Game.h
  src/GameCollection/Tetris/Playfield.cpp
  src/GameCollection/Tetris/Tetromino.h
  src/GameCollection/Tetris/big_noodle_titling.ttf
Labels: TetrisModule, enhancement

#16 [feature] collection and main method
  src/GameCollection/Collection.cpp
  src/GameCollection/Collection.h
  src/GameCollection/GameCollection.cpp
  src/GameCollection/ICollectionEntry.h
  src/GameCollection/Menu/MenuEntry.cpp
  src/GameCollection/Menu/MenuEntry.h
  src/GameCollection/Tetris/Game.cpp
  src/GameCollection/Tetris/SettingsMenu.cpp
  src/GameCollection/Tetris/SettingsMenu.h
  src/GameCollection/Tetris/TetrisGame.h
  src/GameCollection/Tetris/TetrisLoader.cpp
  src/GameCollection/Tetris/TetrisLoader.h
  src/GameCollection/Tetris/TetrisMenu.cpp
  src/GameCollection/Tetris/TetrisMenu.h
Labels: GameCollection, TetrisModule

#20 Ft scoring patch 2
  src/GameCollection/Tetris/TetrisScore.cpp
  src/GameCollection/Tetris/TetrisScore.h
Labels: TetrisModule

#19 Ft scoring patch 1
  Highscores.txt
  src/GameCollection/Tetris/Game.cpp
  src/GameCollection/Tetris/Playfield.cpp
  src/GameCollection/Tetris/TetrisScore.cpp
  src/GameCollection/Tetris/TetrisScore.h
Labels: TetrisModule

#22 changed tetris game controll
  Makefile.am
  src/GameCollection/Menu/MenuEntry.h
  src/GameCollection/Tetris/Game.cpp
  src/GameCollection/Tetris/Game.h
  src/GameCollection/Tetris/SettingsMenu.cpp
  src/GameCollection/Tetris/SettingsMenu.h
  src/GameCollection/Tetris/TetrisLoader.cpp
  src/GameCollection/Tetris/TetrisMenu.cpp
  src/GameCollection/Tetris/TetrisMenu.h
  test.jpeg
Labels: TetrisModule
